### PR TITLE
Dynamic custom highlights

### PR DESCRIPTION
**Pull request by har7an**
Hello,

yesterday, while working in the bright sun, I tried out the light theme variant for the first time. While it makes working in the sun comfortable, I noticed that it doesn't go well at all with my tabline plugin. That's because I overrode the `TabLine*` highlight groups myself, because I wanted their colors changed slightly.

I did this with a config snippet as follows:

```lua
                    TabLine = {
                        fg = colors.main.gray,
                        bg = colors.editor.bg,
                        italic = true
                    },
```

Where `colors` is defined further up as `local colors = require("material.colors");`. Of course, in this case, when switching themes, the change in colors isn't recognized, since `colors` is a local variable in my setup function.

To change that I patched the setup function `apply_highlights` to accept functions as values for custom highlights. In my current design, these functions receive as argument the themes colors and the themes highlights. This would allow me to rewrite my above example as either:

```lua
TabLine = function(col, _)
    return {
        fg = col.main.gray,
        bg = col.editor.bg,
        italic = true
    }
end,
```

or

```lua
TabLine = function(_, hl)
    return vim.tbl_extend("force", hl.main_highlights.editor().Tabline, { italic = true })
end
```

where either approach results in theme colors being applied correctly when changing themes at runtime.

If you prefer, I can also change the design to e.g. make the value of `custom_highlights` in the config a function, which must return a table with all the custom highlight groups (similar to how `custom_colors` works today).

If you'd like to include this patch, I'll update the docs and include these examples there so users can discover the change more easily. Let me know what you think!

### CODE REVIEW

**Comment by marko-cerovac** [comment]
Okay, seems good. But, I would get rid of the deep copy for the highlights and colors because it's a relatively big amount of data to copy over just to make sure the user won't modify the values by accident. A very small number of users actually modify something using ```custom_highlights``` and those that do, usually know what they are doing. So I find it a bit wasteful to do a deep copy of those tables for every user and every call to ```:colorscheme material```. For now, I would get rid of it and if someone does modify default values by accident it's pretty straightforward to diagnose, and they can always open up a github issue and get help.

**Comment by har7an** [comment]
@marko-cerovac Fair point, I removed the deepcopy. Where/how would you like to have this feature documented? I can work out a proposal tomorrow.

**Comment by har7an** [comment]
@marko-cerovac I added examples showing off the new feature in both the README (514277b) and vimdoc (af35238). Are these alright for you?

**Comment by marko-cerovac** [comment]
This is some awesome work. Thanks a lot. If you have any more ideas for improvement, feel free to contribute or open up an issue. I've been busy with exams lately so any help with the plugin is very welcome.

**Review by marko-cerovac — APPROVED** [review]

**Comment by har7an** [comment]
Thanks, I'll definitely do that. Best of luck for your exams!

**Pull request merged**
