### PR TITLE
fixed toggle function setting same style twice

### PR DESCRIPTION
**Pull request by Chaitanyabsprip**
fixed toggle function setting same style twice and added option to print name of style when toggling the styles.

### CODE REVIEW

**Review by marko-cerovac — APPROVED** [review]
Thanks, I haven't got around to working on that. This is just what I had in mind

**Comment by marko-cerovac** [comment]
I've removed the toggle_style function's parameter because it printed the new style twice when called and had a slight lag because of that.

Now, you just call it without passing true as a parameter.

**Comment by Chaitanyabsprip** [comment]
> I've removed the toggle_style function's parameter because it printed the new style twice when called and had a slight lag because of that.
> 
> Now, you just call it without passing true as a parameter.

I didn't notice this behaviour. neither the print happeneing twice nor the lag.

**Comment by marko-cerovac** [comment]
Well that's weird. I got two messages popping up and until I hit enter to dismiss them, the theme did not look right. The switching wasn't quick and seamless as it was before.

**Comment by Chaitanyabsprip** [comment]
for some reason it was not printing it twice for me, either way, it was a bug that I added the printing twice, but there sure was no lag.

**Pull request merged**
