### PR TITLE
Add lighter high contrast theme

### PR DESCRIPTION
**Pull request by rti**
Hi,

first of all, thanks a lot for this great plugin.

This PR adds another light theme, because I found the light theme available a bit low on contrast.

Based on the current light theme, I added another one with stronger contrasts in order to be easier on the eyes.

Maybe this could be useful to somebody.

Screenshot from 2021-05-13 22-55-17

### CODE REVIEW

**Review by marko-cerovac — APPROVED** [review]
Thank you very much, this is great work and it will make a fine addition to the theme. I'll only make one small change. Since I'm trying to keep the theme as true to the [original](https://www.material-theme.com/docs/reference/color-palette/) as possible, I really want to keep only the five original variations. However, I think this is an awesome fix and the best way to go about this (in my opinion) would be to add a new option like
```lua
vim.g.material_lighter_contrast = true
```
When this is set to true, the lighter style uses the new colors that you added. I think it just makes the theme more uniform and on track. What do you think of this proposal? Do you agree?

**Comment by rti** [comment]
@marko-cerovac Thanks a lot for the fast reaction and the kind words. I perfectly understand your approach to keep the original colors and really appreciate adding this color scheme anyway as an additional option for the lighter theme.

Also, thanks a lot for the link to the material color palette.
Would you also accept PRs adding color schemes listed below "Other Themes"? Just asking because I like the "Github" (light) as well.

**Comment by marko-cerovac** [comment]
They are awesome themes, but I wouldn't add them to this repository. If you want, you can copy the code from material.nvim to use as a template for making Github themes. When you have the colors, groups and functions as a template, creating new colorschemes is really easy and fast. A good example of this is [moonlight.nvim](https://github.com/shaunsingh/moonlight.nvim). It was forked from material and turned into a new colorscheme. If you need any help, you can add me as a collaborator on the project.

**Comment by rti** [comment]
Ok. I can perfectly understand that you do not want to add more schemes to this addon.

Also, thanks a lot for offering help. I will let you know when I plan to proceed on this.

**Pull request merged**
